# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: hyperflow-amqp-executor 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "hyperflow-amqp-executor".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kamil Figiela".freeze]
  s.date = "2018-07-21"
  s.description = "AMQP job executor for Hyperflow workflow engine (http://github.com/dice-cyfronet/hyperflow)".freeze
  s.email = "kamil.figiela@gmail.com".freeze
  s.executables = ["hyperflow-amqp-executor".freeze, "hyperflow-amqp-metric-collector".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Dockerfile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/hyperflow-amqp-executor",
    "bin/hyperflow-amqp-metric-collector",
    "example/settings.yml",
    "example/task.json",
    "hyperflow-amqp-executor.gemspec",
    "lib/hyperflow-amqp-executor.rb",
    "lib/hyperflow-amqp-executor/cloud_storage.rb",
    "lib/hyperflow-amqp-executor/database_loger.rb",
    "lib/hyperflow-amqp-executor/gridftp_storage.rb",
    "lib/hyperflow-amqp-executor/helpers.rb",
    "lib/hyperflow-amqp-executor/job.rb",
    "lib/hyperflow-amqp-executor/local_storage.rb",
    "lib/hyperflow-amqp-executor/nfs_storage.rb",
    "lib/hyperflow-amqp-executor/plgdata_storage.rb",
    "lib/hyperflow-amqp-executor/settings.rb",
    "test/helper.rb",
    "test/test_hyperflow-amqp-executor.rb"
  ]
  s.homepage = "http://github.com/kfigiela/hyperflow-amqp-executor".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "AMQP job executor for Hyperflow workflow engine".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fog>.freeze, ["~> 1.18"])
      s.add_runtime_dependency(%q<unf>.freeze, ["~> 0.1"])
      s.add_runtime_dependency(%q<recursive-open-struct>.freeze, ["~> 0.4"])
      s.add_runtime_dependency(%q<amqp>.freeze, ["~> 1.1"])
      s.add_runtime_dependency(%q<deep_merge>.freeze, ["~> 1.0"])
      s.add_runtime_dependency(%q<httpclient>.freeze, ["~> 2.6"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 1.8.7"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
    else
      s.add_dependency(%q<fog>.freeze, ["~> 1.18"])
      s.add_dependency(%q<unf>.freeze, ["~> 0.1"])
      s.add_dependency(%q<recursive-open-struct>.freeze, ["~> 0.4"])
      s.add_dependency(%q<amqp>.freeze, ["~> 1.1"])
      s.add_dependency(%q<deep_merge>.freeze, ["~> 1.0"])
      s.add_dependency(%q<httpclient>.freeze, ["~> 2.6"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 1.8.7"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<fog>.freeze, ["~> 1.18"])
    s.add_dependency(%q<unf>.freeze, ["~> 0.1"])
    s.add_dependency(%q<recursive-open-struct>.freeze, ["~> 0.4"])
    s.add_dependency(%q<amqp>.freeze, ["~> 1.1"])
    s.add_dependency(%q<deep_merge>.freeze, ["~> 1.0"])
    s.add_dependency(%q<httpclient>.freeze, ["~> 2.6"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.8.7"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
  end
end

